name: Update index.html

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if script tag exists
        run: |
          # I did not find a way to add the script line permanently to the head. This action adds it again after each push to master.
          if ! grep -q '<script defer data-domain="notes.felixzieger.de" src="https://plausible.sonnenhof-zieger.de/js/script.js"></script>' index.html; then
            echo "Script tag not found, adding it."
            sed -i 's/<\/head>/<script defer data-domain="notes.felixzieger.de" src="https://plausible.sonnenhof-zieger.de/js/script.js"><\/script><\/head>/' index.html
          else
            echo "Script tag already exists, no need to add."
          fi

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add index.html
          git commit -m "add plausible header"
          git push
